<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casino [
        <!ELEMENT casino (game)*>
        <!ELEMENT game (gamename|gameid|userid|session)*>
        <!ELEMENT gamename (#PCDATA)>
        <!ELEMENT gameid (#PCDATA)>
        <!ELEMENT session (datetime|sessionid|userid)*>
        <!ELEMENT datetime (#PCDATA)>
        <!ELEMENT sessionid (#PCDATA)>
        <!ELEMENT userid (#PCDATA)>
        ]>
<casino>
    <game>
        <gamename>black jack</gamename>
        <gameid>g1</gameid>
        <userid>d1</userid>
        <session>
            <datetime>2020-08-10T18:45:10</datetime>
            <sessionid>ss1</sessionid>
            <userid>c1</userid>
        </session>
        <session>
            <datetime>2020-08-10T18:45:10</datetime>
            <sessionid>ss2</sessionid>
            <userid>c2</userid>
        </session>
        <session>
            <datetime>2020-08-13T18:45:10</datetime>
            <sessionid>ss9</sessionid>
            <userid>c3</userid>
        </session>
        <session>
            <datetime>2020-08-14T18:45:10</datetime>
            <sessionid>ss4</sessionid>
            <userid>c4</userid>
        </session>
    </game>
    <game>
        <gamename>baccarat</gamename>
        <gameid>g2</gameid>
        <userid>d1</userid>
        <session>
            <datetime>2020-08-10T18:10:15</datetime>
            <sessionid>ss3</sessionid>
            <userid>c2</userid>
        </session>
        <session>
            <datetime>2020-08-12T19:00:00</datetime>
            <sessionid>ss6</sessionid>
            <userid>c1</userid>
        </session>
        <session>
            <datetime>2020-08-12T19:00:00</datetime>
            <sessionid>ss7</sessionid>
            <userid>c1</userid>
        </session>
        <session>
            <datetime>2020-08-16T19:00:00</datetime>
            <sessionid>ss8</sessionid>
            <userid>c1</userid>
        </session>
    </game>
</casino>